name: ALZ Vending Pipeline

on: [workflow_dispatch]

env:
  ManagementGroupPrefix: "alz"
  location: "swedencentral"
  runNumber: ${{ github.run_number }}

jobs:
  bicep_tenant_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
                
      - name: Deploy Landing Zone
        id: deploy_landing_zone
        uses: azure/arm-deploy@v1
        with:
          scope: managementgroup
          managementGroupId: ${{ env.ManagementGroupPrefix }}
          region: ${{ env.location }}
          template: main.bicep
          parameters: landingZones/lz2.parameters.json
          deploymentName: Landing-Zone-${{ env.runNumber }}
          failOnStdErr: false
